services:
  app:
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - db
      - nats
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
  db:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"