services:
  app:
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/cmd/.env:rw
    ports:
      - "50051:50051"
    depends_on:
      - nats
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
