services:
  app:
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/cmd/.env:rw
    ports:
      - "50051:50051"
    depends_on:
      - nats
    networks:
      - my_network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - my_network
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
    external: true