services:
  app:
    image: trips-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/cmd/.env:rw
    ports:
      - "50053:50051"

    networks:
      - my_network



networks:
  my_network:
    driver: bridge
    external: true