services:
  app:
    image: trips-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/cmd/.env:rw
    ports:
      - "50051:50051"
    depends_on:
      - mongo
      - redis
      - nats
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"