services:
  app:
    image: user-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/cmd/.env:rw
    ports:
      - "50051:50051"
    depends_on:
      - nats
      - mongo
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"