services:
  app:
    image: user-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/cmd/.env:rw
    ports:
      - "50054:50051"

    networks:
      - my_network



networks:
  my_network:
    driver: bridge
    external: true